---
title: "Statistical Learning"
description: |
  Master Degree in Statistics and Economics, University of Milano-Bicocca 
author:
  - name: Aldo Solari
    url: https://aldosolari.github.io/
    affiliation: DEMS
    affiliation_url: https://www.unimib.it/ateneo/dipartimenti-e-scuole/alla-scoperta-%E2%80%A6/dipartimento-economia-metodi-quantitativi-e-strategie-impresa
date: "`r Sys.Date()`"
output:
  radix::radix_article:
    toc: true
    toc_depth: 1
---

*Big Data*, *Deep Learning* and *Data Science* have now become recurring terms in media communication. In response to the growing need to analyze data, the profession of the *data scientist* has recently emerged. This course aims to provide new tools for the data scientist. These tools require technical skills such as programming and statistics. They also require professional skills such as communication, teamwork, problem solving, and critical thinking. See the [course syllabus](https://aldosolari.github.io/SL/syllabus/syllabus.html) for further information.

The topics covered by this course are

* *Advanced statistical/machine learning models*: GAMs, boosting algorithms, ensemble learning
* *Large-scale testing* and *selective inference*
* *High-dimensional inference*:  sample-splitting inference, stability selection, knockoffs

The final project is to do a novel data analysis and write a blog post about it. See the [#Final](#final) section for more details.

| When | Where | Hours |
|---|---|----|
| Monday | Lab713 | 13:30-16:30 |
| Wednesday | Lab713 | 15:30-18:30|
| Thursday | Lab713 | 12:30-14:30|


# Latest announcements

* No news.

# Course Material

Most of the course material can be found in the slides linked to below. The slides are supplemented by readings which are listed in the [#Reading](#reading) section.

| N | Date |  Lecture |  Slides | 
|--|--|--------------|--------|
| 1 | Dicember 3 | Introduction | [Slides](docs/slides/1_Intro/1_Intro.html) |  
| 2 | Dicember 5 | Regression and smoothing splines | [Slides](docs/slides/2_Splines/2_Splines.html) | 
| 3 | Dicember 6 | Generalized additive models | [Slides](docs/slides/3_GAM/3_GAM.html) | 
||||
| 4 | Dicember 10 | Boosting with squared-error loss | [Slides](docs/slides/4_L2boost/4_L2boost.html) | 
| 5 | Dicember 12 | Ensemble learning | [Slides](docs/slides/5_Ensemble/5_Ensemble.html) | 
| 6 | Dicember 13 | Effective communication | [Slides](docs/slides/6_Communication/6_Communication.pdf) | 
|||||
| 7 | January 7 | Large-scale testing | [Slides](docs/slides/7_Large/7_Large.html) | 
| 8 | January 9 | The false discovery rate | [Slides](docs/slides/8_FDR/8_FDR.html) | 
| 9 | January 10 | Selective inference |[Slides](docs/slides/9_Selective/9_Selective.html) | 
|||||
| 10 | January 14 | Sample-splitting inference | [Slides](docs/slides/10_Split/10_Split.html) | 
| 11 | January 16 | Stability selection | [Slides](docs/slides/11_Stability/11_Stability.html) | 
| 12 | January 17 | Knockoffs | [Slides](docs/slides/12_Knockoffs/12_Knockoffs.html) | 
|||||
| 13 | January 21 | Projects discussion | - | 
| 14 | January 23 | Projects presentation | - | 
| 15 | January 24 | Projects presentation | - | 
|||||
| 16 | January 28 | Projects presentation | - |  

All of the course material is on the [github repo](https://github.com/aldosolari/SL). 

# Reading

There are two primary references:

* [Computer-Age Statistical Inference](https://web.stanford.edu/~hastie/CASI/) (CASI)
* [The Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/) (ESL)

Calendar:

**December 3** Introduction

  - CASI 1, 1.1 (pages 3-8), 4.3 (pages 45-46)

**December 5** Regression and smoothing splines

  - ESL 5, 5.1, 5.2, 5.2.1, 5.2.2, 5.4, 5.4.1
  
**December 6** Generalized additive models

  - ESL 5.7, 9.1, 9.1.1, 9.1.2, 9.1.3

**December 10** Boosting with squared-error loss

  - CASI 17.2
  
**December 12** Ensemble learning

  - CASI 17.3, 17.4
  - ESL 8.8, 16.1
  
**December 13** Effective communication

  - [So what?](http://www.storytellingwithdata.com/blog/2017/3/22/so-what)
  - [How to ask](https://stackoverflow.com/help/how-to-ask)

**January 7** Large-scale testing

  - CASI 1.2, 15.1
  
**January 9** The false discovery rate

  - CASI 15.2

**January 10** Selective inference

  - CASI 20.1
  
**January 14** Sample-splitting inference

  -  [Dezeure et al. (2015) Statistical Science](https://projecteuclid.org/download/pdfview_1/euclid.ss/1449670857), sections 1, 2, 2.1.1
  
  
**January 16** Stability selection

- [Meinshausen and Bühlmann (2010) JRSS-B](https://stat.ethz.ch/~nicolai/stability.pdf)

**January 17** Knockoffs

- Model-X knockoffs: [Candès et al. (2018) JRSSB](https://statweb.stanford.edu/~candes/papers/MF_knockoffs.pdf)

**January 23** Projects presentation

  - Teams: GS, GreenTeam, Humans, Clothster Analysis, JANUARY, PowerTrasform

**January 24** Projects presentation

  - Teams: Hermani, The_Regressionists, Anonymous, Robaskol
  
**January 28** Projects presentation: 

  - Teams: D, MSF, CaMelos', IGA, Random_Forest_512, BoxCox


# Final project

Your final project is to do a __novel data analysis__ to answer a __question__ and write a __blog post__ about it on github. This can be interpreted broadly and the requirements are discussed below.

Examples might include:

* put together a novel data set (e.g. scrape something from the web)
* answer an interesting question
* a sophisticated statistical/machine learning model
* a really compelling visualization
* write a shiny app

The rough outline of the project is: Start with a question. Find data that might get at that question. Play around with the data. Attempt to answer the question. Iterate. Communicate. At the end you should produce:

1. Blog post

2. Analysis document


### Blog post

The blog post should answer:

* What is the question(s) you tried to answer? Why should someone care?

* What are your findings?

The blog post should be aimed at a general audience who is not afraid of graphs/a little data. 

* The post should be 1000-1500 words (unless you made a shiny app)
    - Include a title and your names
    - Don’t display R code unless it is used to convey a point

* There should be at least one visualization
    - Make sure to describe the figures somewhere in the text
    - These plots should be communicatory plots, not exploratory plots
    
* The post should be submitted in html (probably written in R Markdown)

### Analysis document

The analysis document should detail the steps you took to develop the blog post. This includes where you got the data, other solutions you tried, the statistical methods you chose and your findings. The document should contain the following topics (depending on the project some of these will be more important than others): 

* Overview and Motivation: Provide an overview of the project goals and the motivation for it

* Data: What is the data/how did you get it?

* Statistical methods: How did you answer the questions (e.g. what statistical techniques, etc)? It should include text justifying decisions you made (e.g. why did you remove certain observations, etc.)

* Related Work: Anything that inspired you, such as a paper, a web site,  something we discussed in class, etc. 

* All the code used to produce the blog post from the raw data should be available on github


### Grading

| Dimension | details | 
|---|---|
| Project | States the objective, able to identify relevant questions |
|  | Creativity | 
|  | Effort | 
| Blog | Is the post written well and clearly?  |
| | Material included is relevant to the overall message/purpose? |
|  | Quality of figures  |
| Statistics | Statistical methods and/or critical thinking adequate? |
|  | Is the data analysis well grounded? |
|  | How well do the findings support the conclusions?   |
| Communication | Does the main point come through? |
|  | Were the main ideas presented in an orderly and clear manner? |
|  | Did the talk maintain the interest of the audience? |
|  | Were the slides (or another instrument) appropriate and helpful to the audience? |
|  | Were the presenters responsive to audience questions? |



### Resources

The following resources may help with the project.

Blog posts

* [Polygraph](http://polygraph.cool/)
* [FiveThirtyEight](https://fivethirtyeight.com/)
* [Normal Deviate](https://normaldeviate.wordpress.com/)

Books

* [Data Science in R: A Case Studies Approach to Computational Reasoning and Problem Solving](http://rdatasciencecases.org/) 
* [Modern Data Science with R](https://mdsr-book.github.io/) 

Newspapers

* [Infodata](http://www.infodata.ilsole24ore.com/?refresh_ce=1)
* [Economist](https://www.economist.com/graphic-detail/2018/11/24/tvs-golden-age-is-real)

Video 

* [The Fallen of World War II](https://vimeo.com/128373915)

# Exam

Exams schedule:

| N.ro |When | Where | Hour |
|---|---|---|---|---|
| 1 | 8/2/2019 | U7/13 | 14:00 |
| 2 | 21/2/2019 | U7/13 | 14:00 |
| 3 | 29/4/2019 | TBD | 14:00 |
| 4 | 1/7/2019 | U7/17 | 10:00 |
| 5 | 15/7/2019 | U7/16 | 14:00 |
| 6 | 18/9/2019 | U6/36 | 10:00 |

The exam consists of two parts:

- __Written exam__ (open-ended and/or closed-ended questions)

- __Oral exam__, including the __presentation__ of a data science __project__ (homework)
    - Attending students can form a __team__ (max. 3 persons) and present at the end of the course. In this case the oral exam is optional

The final grade is a weighted average of written exam (1/2) and oral exam (1/2). 


### Past exams:

* Statistical Learning 08/02/2019 : [Marks](exams/SL080219/esiti_SL080219.pdf)

* Data Science 08/02/2019 : [Marks](exams/DS080219/esiti_DS080219.pdf)

* Statistical Learning 21/02/2019 : [Marks](exams/SL210219/esiti_SL210219.pdf)

* Data Science 21/02/2019 : [Marks](exams/DS210219/esiti_DS210219.pdf)

* Statistical Learning 29/04/2019 : [Marks](exams/SL290419/esiti_SL290419.pdf)

* Data Science 29/04/2019 : [Marks](exams/DS290419/esiti_DS290419.pdf)

* Statistical Learning 01/07/2019 : [Marks](exams/SL010719/esiti_SL010719.pdf)

* Data Science 05/07/2019 : [Marks](exams/DS050719/esiti_DS050719.pdf)

* Data Science 16/07/2019 : [Marks](exams/DS160719/esiti_DS160719.pdf)


# Blogs

[List of partecipants](docs/projects/SLteams.pdf)

[Evaluation](docs/projects/blogs.html)


- [Anonymous](https://susannapanizza.shinyapps.io/DoveAndiamoAMangiare/) [ Appendix [a](https://marcoabbiati.github.io/SL/Documento_di_analisi.html), [b](https://github.com/marcoabbiati/SL) ]

- [BoxCox](https://danieleparimbelli95.github.io/SLproject/Blog_Post.html) [ Appendix [a](https://danieleparimbelli95.github.io/SLproject/Analysis_Document.html), [b](https://danieleparimbelli95.github.io/SLproject/Code.html) ]

- [CaMelos’](https://alicegiampino.github.io/SL/) [ Appendix [a](https://alicegiampino.github.io/SL/metodologia.html),  [b](https://github.com/AliceGiampino/SL) ]

- [Clothster Analysis](https://clothsteranalysis.wordpress.com/) [ Appendix [a](https://github.com/ArguirovK/ClothsterAnalysis), [b](https://arguirovk.github.io/ClothsterAnalysis/ClusterRMD.html), [c](https://drive.google.com/file/d/1HLafJEPtmLbN_5p6D9ZS92JQpfWW-Rd-/view), [d](https://drive.google.com/open?id=1EASe_oh9KcCFD-ig5IoKVaaHFGShw_77)  ]

- [D](https://daniloperrini1.github.io/stat-learning/tuft.html) [ Appendix [a](https://daniloperrini1.github.io/stat-learning/slide_presentazione.pdf), [b](https://daniloperrini1.github.io/stat-learning/screen_app.png), [c](https://daniloperrini1.github.io/stat-learning/codice_completo.R) ]                

- [GreenTeam]( https://nicholasmissineo.github.io//progetto_statistical_learning//SL_BLOG.html) [ Appendix [a](https://nicholasmissineo.github.io//progetto_statistical_learning//Analysis_document.html), [b](https://github.com/nicholasmissineo/progetto_statistical_learning) ]

- [GS](https://convnets578736054.wordpress.com/) [ Appendix [a](marcellosbordi.github.io/ConvNets.pdf) ]

- [Hermani](https://cacio95.github.io/StatisticalLearningProject/Birraebasket.html) [ Appendix [a]( https://cacio95.github.io/StatisticalLearningProject/report/Birraebasket-report.html), [b](https://github.com/cacio95/StatisticalLearningProject) ]


- [Humans](https://fabiomarigo7.github.io/popolarita-nel-calcio/) [ Appendix [a](https://github.com/fabiomarigo7/popolarita-nel-calcio/tree/master/source) ]

- [IGA]( https://alessandrapellegata.shinyapps.io/meteoriti/) [ Appendix [a](https://alessandra-pellegata.github.io/SL_Project/Meteoriti_DocAnalysis.html), [b](https://github.com/alessandra-pellegata/SL_Project) ] 

- [JANUARY](https://letiziagiordano.github.io/SL/BLOG.html) [ Appendix [a](https://github.com/letiziagiordano/SL) ]

- [MSF](https://martinacaronte.shinyapps.io/projectsl2/) [ Appendix [a](https://sarasixti.github.io/SLproject/European_history_docanalysis.html), [b](https://sarasixti.github.io/SLproject/European_history_docanalysis_p2.html), [c](https://sarasixti.github.io/SLproject/European_history_docanalysis_p3.html) ]

- [PowerTrasform](https://github.com/Damiano95/SL/blob/master/Codici%20e%20document%20analysis/Screen%20progetto.pdf) [ Appendix [a]( https://github.com/Damiano95/SL/blob/master/Codici%20e%20document%20analysis/Document_Analysis.pdf
) ]

- [Random_Forest_512](https://giacomosaccaggi.github.io/Films/)

- [Robaskol](https://aongaro3.github.io/ProgettoSL/BlogPost.html) [ Appendix [a](https://github.com/AOngaro3/ProgettoSL/blob/master/DocAnalysis/AnalysisDocument.pdf) ]

- [The_Regressionists](https://chiaracrippa.github.io/blog/index.html) [ Appendix [a](https://chiaracrippa.github.io/blog/document/Analysis%20document.pdf), [b](https://github.com/ChiaraCrippa/blog/tree/master/code%20and%20results) ]



## Acknowledgments {.appendix}

Much of the course content was inspired by the following courses:

* [STOR 390: Introduction to Data Science](https://idc9.github.io/stor390/)
* [36-402: Undergraduate Advanced Data Analysis](http://www.stat.cmu.edu/~cshalizi/uADA/17/)
* [Generalized Additive Models](https://m-clark.github.io/generalized-additive-models/)
* [Stats 300C: Theory of Statistics](https://statweb.stanford.edu/~candes/stats300c/)
* [BIOS 7600: High Dimensional Data Analysis](http://myweb.uiowa.edu/pbreheny/7600/s16/notes.html)


and on a number of other sources. 




## Disclaimer {.appendix}

The course material contains images obtained by routine Google Images searches. 
Some of these images may perhaps be copyright. They are included here for
educational noncommercial purposes and are considered
to be covered by the doctrine of Fair Use. In any event
they are easily available from Google Images.
It’s not feasible to give full scholarly credit to the
creators of these images. We hope they can be satisfied
with the positive role they are playing in the educational
process.
