---
title: "XYZ"
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## Spurious association

Suppose that $Y\bot Z$ and $Y \leftarrow X \rightarrow Z$. In particular, consider the linear model
$$Y = \beta_x X + \beta_z Z + \varepsilon$$ where $\beta_x = 1$ and $\beta_z = 0$.
If we consider the submodel 
$$Y = \tilde{\beta}_x X  + \tilde{\varepsilon}$$
then it may be that $\tilde{\beta_x} \neq 0$. 

```{r, message=FALSE, warning=FALSE, comment=FALSE}
rm(list=ls())
library(MASS)
n = 200
set.seed(2)

x = rnorm(n)
z = x + rnorm(n,0,0.5)
X = cbind(x,z)
beta = c(1,0) 
y = X %*% beta + rnorm(n)
p=2

M = 1
X_M = X[,M]
P_M = X_M %*% solve(t(X_M)%*% X_M) %*% t(X_M)
ginvX_M = ginv(X_M)
beta_M = rep(0,p)
beta_M[M] = ginvX_M %*% P_M %*% X %*% beta
rbind(beta,round(beta_M,2))

round(summary(lm(y ~ 0+X_M))$coef,4)
round(summary(lm(y ~ 0+X))$coef,4)

M = 2
X_M = X[,M]
P_M = X_M %*% solve(t(X_M)%*% X_M) %*% t(X_M)
ginvX_M = ginv(X_M)
beta_M = rep(0,p)
beta_M[M] = ginvX_M %*% P_M %*% X %*% beta
rbind(beta,round(beta_M,2))


round(summary(lm(y ~ 0+X_M))$coef,4)
round(summary(lm(y ~ 0+X))$coef,4)
```

## Another example

```{r, message=FALSE, warning=FALSE, comment=FALSE}
rm(list=ls())

n = 100
p = 3
beta = c(-1,2,0)

set.seed(2)
rho = 0.9
R = matrix(rho,ncol=p,nrow=p) + diag(rep(1-rho,p))
X = mvrnorm(n, mu=rep(0,p), Sigma=R)

y = X%*%beta + rnorm(n)

M = c(1,2)
X_M = X[,M]
P_M = X_M %*% solve(t(X_M)%*% X_M) %*% t(X_M)
ginvX_M = ginv(X_M)
beta_M = rep(0,p)
beta_M[M] = ginvX_M %*% P_M %*% X %*% beta
rbind(beta,round(beta_M,2))

M = c(1,3)
X_M = X[,M]
P_M = X_M %*% solve(t(X_M)%*% X_M) %*% t(X_M)
ginvX_M = ginv(X_M)
beta_M = rep(0,p)
beta_M[M] = ginvX_M %*% P_M %*% X %*% beta
rbind(beta,round(beta_M,2))

round(summary(lm(y ~ 0+X_M))$coef,4)
round(summary(lm(y ~ 0+X))$coef,4)
```