---
title: "Variable Selection Algorithms"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

### Variable Selection Algorithms

```{r, message=FALSE, warning=FALSE}
n = 25
p = 100
s = 5

set.seed(123)
X = matrix(runif(n*p), ncol=p)
colnames(X) = paste0("X",1:p)
beta = c(rep(2,s),rep(0,p-s))
y =  2 + X %*% beta + rnorm(n)

# forward
fml.full <- as.formula(paste("y ~ ", paste(colnames(X), collapse= "+"))) 
fit.fwd <- step(lm(y~1,as.data.frame(X)), scope=fml.full, direction="forward", steps=s, trace=0)
hatS.fwd <- attr(fit.fwd$coefficients, "names")[-1]
hatS.fwd


# lasso
library(glmnet)
lasso <- glmnet(X,y, alpha=1, dfmax=s)
lambda = lasso$lambda[which.max(lasso$df>=s)]
hatS.lasso = colnames(X)[which(coef(lasso, s=lambda)[-1]!=0)]
hatS.lasso

# marginal
pvals = sapply(1:p, function(j) summary(lm(y ~ X[,j]))$coefficients[2,4]) 
hatS.marg = paste("X", order(pvals)[1:s], sep="")
hatS.marg 
```

### Inference after Variable Selection

```{r, message=FALSE, warning=FALSE}
# true model fit
fit.true = lm(y~ X1+X2+X3+X4+X5, as.data.frame(X))
summary(fit.true)
confint(fit.true)

# fit of the model selected by Forward Stepwise
summary(fit.fwd)

# fit of the model selected by Lasso
fml.lasso = paste("y ~ ", paste(hatS.lasso, collapse="+"))
summary(lm(fml.lasso, data.frame(X) ))

# fit of the model selected by Marginal regression
fml.marg = paste("y ~ ", paste(hatS.marg, collapse="+"))
summary(lm(fml.marg, data.frame(X) ))

```
