---
title: "**Syllabus**"
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float: yes
---

| Insegnamento | Modulo | CFU | ID |
|----|--------|--------|--------------|
| DATA SCIENCE M | [STATISTICAL LEARNING](https://aldosolari.github.io/SL/) | 6 | 1819-2-F8204B018-F8204B034M |
| [STATISTICAL LEARNING M](https://aldosolari.github.io/DM/)  | | 6 | 1819-2-F8204B018-F8204B033M |

# **Obiettivi formativi**

*Big Data* e *Data Science* sono ormai diventati termini ricorrenti nella comunicazione mediatica (internet, tv, radio, giornali etc.). In risposta all'esigenza sempre più crescente di analizzare dati, è emersa la figura dello "scienziato dei dati" (*data scientist*),  professione che richiede competenze trasversali (informatiche, matematico-statistiche, di comunicazione) e una forma mentis scientifica. Il corso si pone come obiettivo  quello di fornire nuovi strumenti per affrontare l'analisi di dati complessi. Durante il corso verranno discussi alcuni casi studio.

Lo studente, al termine del corso, avrà perfezionato le abilità di problem solving e di programmazione in R e sarà in grado di utilizzare metodi statistici avanzati per trarre conclusioni sui dati. 

# **Contenuti sintetici**

Il corso integra considerazioni di carattere teorico con aspetti pratico-applicativi di analisi dei dati e di programmazione in R per facilitare la comprensione degli argomenti trattati.

* Aspetti teorici: modelli statistici avanzati, il problema della molteplicità e della selezione, metodi inferenziali moderni per l'analisi di dati ad elevata dimensionalità
* Aspetti applicativi: implementazione dei metodi e presentazione di casi studio in R

# **Programma esteso**

* Modelli statistici avanzati: generalized additive models, boosting algorithms, stacked regression, support vector machines, deep learning (cenni)
* Il problema della molteplicità e della selezione
* Inferenza per modelli ad elevata dimensionalità: high-dimensional global test, sample-splitting inference, stability selection, knockoffs (cenni)
* Casi studio in R

# **Prerequisiti** 

Si consiglia la conoscenza degli argomenti trattati nei corsi *Probabilità e Statistica Computazionale M*, *Statistica Avanzata M* e nel modulo *Data Mining* del corso *Data Science M*.

# **Metodi didattici**

Le lezioni si svolgono in laboratorio, integrando aspetti di carattere teorico con quelli pratico-applicativi di analisi dei dati e di programmazione in R.

# **Modalità di verifica dell'apprendimento**

La modalità di verifica si basa su 

1. una prova scritta
2. una prova orale, comprendente la presentazione di un caso di studio

Il voto complessivo è dato dalla media dei voti delle parti 1. e 2. 

La prova scritta si svolge in aula e comprende domande aperte e/o a scelta multipla, ed ha come obiettivo la verifica della comprensione degli argomenti trattati. 

La prova orale prevede la presentazione di un caso di studio ed eventualmente la discussione della prova scritta. L'analisi del caso di studio deve essere preparata prima della prova scritta e deve essere caricata sulla propria pagina github. La presentazione del caso di studio ha come obiettivo la verifica delle abilità di analisi e di comunicazione dei risultati. Agli studenti frequentanti viene data l'opportunità di svolgere la presentazione del caso di studio in aula in gruppi di massimo 3 persone. In questo caso lo studente frequentante deve sostenere solo la prova scritta. 


# **Testi di riferimento**

* Archivio del corso: https://github.com/aldosolari/SL
* Clark (2018) Generalized Additive Models.  https://m-clark.github.io/generalized-additive-models/
* Efron, Hastie (2016) Computer-Age Statistical Inference: Algorithms, Evidence, and Data Science. Cambridge University Press
* Hastie, Tibshirani, Friedman (2009) The Elements of Statistical Learning. Data Mining, Inference and Prediction. Springer
* Nolan, Lang (2015) Data Science in R: A Case Studies Approach to Computational Reasoning and Problem Solving. Chapman and Hall/CRC

# **Periodo di erogazione dell’insegnamento**

Primo semestre, secondo ciclo.

# **Lingua di insegnamento**

Le lezioni si svolgono in italiano, tuttavia la maggior parte dei libri di testo e il materiale didattico è in lingua inglese.